
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bhushan
 */
public class AfterLogin extends javax.swing.JFrame {

    /**
     * Creates new form AfterLogin
     */
    public static String source,destination;
    int fare;
    String alertText;
    public AfterLogin() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.png")).getScaledInstance(600,600, WIDTH));
        fare=0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        locSubmitButton = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 200, 200, 400));
        setPreferredSize(new java.awt.Dimension(641, 290));
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..............To.............", "MIT", "Deccan", "Baner" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(400, 100, 201, 36);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..............From.............", "MIT", "Deccan", "Baner" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(60, 100, 201, 36);

        locSubmitButton.setText("ESTIMATE FAIR");
        locSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locSubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(locSubmitButton);
        locSubmitButton.setBounds(230, 200, 160, 29);
        getContentPane().add(label1);
        label1.setBounds(366, 243, 212, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/step0002.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -60, 670, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed

        
        AfterLogin.source=jComboBox3.getSelectedItem().toString();
        //System.out.println("Source: "+source);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

 AfterLogin.destination=jComboBox2.getSelectedItem().toString();
        //System.out.println("Destination: "+destination);
        if(AfterLogin.source.equals(AfterLogin.destination))
        {
            alertText="Source and destination cannot be same";
            JOptionPane.showMessageDialog(rootPane,alertText);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void locSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locSubmitButtonActionPerformed
        
        AfterLogin.source=jComboBox3.getSelectedItem().toString();
        AfterLogin.destination=jComboBox2.getSelectedItem().toString();
        estimateFare();
        
        
    }//GEN-LAST:event_locSubmitButtonActionPerformed
    public void estimateFare()
    {
        if(AfterLogin.source.equals("..............From............."))
        {
            alertText="Please specify source";
            JOptionPane.showMessageDialog(rootPane,alertText);
            return;
        }
        if((AfterLogin.destination.equals("..............To.............")))
        {
            alertText="Please specify destination";
             JOptionPane.showMessageDialog(rootPane,alertText);
             return;
        }
        try {
            Main.st=Main.con.createStatement();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AfterLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        String query="Select path from Location1 where source='"+AfterLogin.source+"' and destination='"+AfterLogin.destination+"'";
        try {
            Main.rs =Main.st.executeQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(AfterLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        fare = 0;
        
        try {
            while(Main.rs.next())
            {
                fare=Main.rs.getInt("path");
                System.out.println("fare is "+fare);
       //         label1.setText(Integer.toString(fare));
            }} catch (SQLException ex) {
            Logger.getLogger(AfterLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        Display d=new Display(fare);
        d.setVisible(true);
    }
    public int getFare()
    {
        return fare;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label1;
    private javax.swing.JButton locSubmitButton;
    // End of variables declaration//GEN-END:variables
}
