
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tejashree
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public static int fare;
    public Display()
    {
        initComponents();
    }
    public Display(int fare) 
    {
        Display.fare=fare;
        initComponents();
        displayFare.setText("Your estimated fare is "+fare+" INR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayFare = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 200, 200, 400));
        setPreferredSize(new java.awt.Dimension(641, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        displayFare.setFont(new java.awt.Font("Century Schoolbook L", 1, 30)); // NOI18N
        getContentPane().add(displayFare);
        displayFare.setBounds(90, 110, 491, 67);

        jButton1.setText("BOOK CAB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 220, 161, 57);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/step0002.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -50, 670, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int action=JOptionPane.showConfirmDialog(rootPane,"Are you sure?", "Select an option",JOptionPane.YES_NO_OPTION);
       if(action==JOptionPane.YES_OPTION)
       {
            try {
                Main.st=Main.con.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
            }
            String bookingID=new java.util.Date().toString()+Login.userName;
           int locationID = 0;
           String locationQuery="select LocationID from Location2 where source ='"+AfterLogin.source+"'and destination = '"+AfterLogin.destination+"';";
            System.out.println("Location query is "+locationQuery);
            try
            {
                Main.rs=Main.st.executeQuery(locationQuery);
                while(Main.rs.next())
                {
                    locationID=Main.rs.getInt("LocationID");
                }
                
            }
            catch(SQLException ex)
            {
                
            }
            System.out.println("LocationID is "+locationID);
            
           String query="insert into Booking2(BookingID,LocationID,username,source,destination,path) values('"+bookingID+"',"+locationID+",'"+Login.userName+"','"+AfterLogin.source+"','"+AfterLogin.destination+"','"+Display.fare+"')";
           System.out.println("query is "+query);
            int i;
            try {
                i = Main.st.executeUpdate(query);
            } catch (SQLException ex) {
                Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
            }
            //System.out.println(i);
            
           JOptionPane.showMessageDialog(rootPane, "Cab is booked !");
           this.setVisible(false);
           AfterBooking a=new AfterBooking();
           a.setVisible(true);
       }
//       else if(action==JOptionPane.NO_OPTION)
//       {
//           this.setVisible(false);
//           AfterBooking b=new AfterBooking();
//           b.setVisible(true);
//       }
//       else if(action==JOptionPane.CANCEL_OPTION)
//       {
//            this.setVisible(false);
//            AfterLogin a=new AfterLogin();
//            a.setVisible(false);
//       }
           
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayFare;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
